[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.28.0"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "aarch64-unknown-linux-gnu", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu"]
# Path that installers should place binaries in
install-path = "CARGO_HOME"
# Whether to install an updater program
install-updater = false

github-build-setup = "build-workaround"

allow-dirty = ["ci"]

[dist.bin-aliases]
firepit = ["fire"]

# TODO: fix this
# cf. https://github.com/axodotdev/cargo-dist/issues/1760
[dist.github-custom-runners]
global = "ubuntu-latest"

# TODO: fix this
# cf. https://github.com/axodotdev/cargo-dist/issues/1760
[dist.github-custom-runners.x86_64-unknown-linux-gnu]
runner = "ubuntu-latest"

# TODO: fix this
# cf. https://github.com/axodotdev/cargo-dist/issues/1760
[dist.github-custom-runners.aarch64-unknown-linux-gnu]
runner = "ubuntu-latest"
